### ISSUE TITLE
Льняное масло нельзя подвергать термообработке

### ISSUE THREAD

**Issue by philip-bl** [l29ah/muesli#7]
На бутылке льняного масла написано ${сабж}, но muesli предполагают заливание в хлопья с льняным маслом кипятка. А это термообработка.

**Comment by l29ah** [comment]
On Sat, Nov 04, 2017 at 07:43:10AM +0000, philip-bl wrote:
> На бутылке льняного масла написано ${сабж}, но muesli предполагают заливание в хлопья с льняным маслом кипятка. А это термообработка.

Льняное масло не охуевает от сотни цельсиев ненадолго. Вот жарить на нём ничего точно не стоит.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by philip-bl** [comment]
Я сегодня залил немношк в быстроприготавливаемую овсянку, долил кипятка, и на вкус оно немношк охуело. Впрочем попробую еще залить после остывания и сравню на всяк. случай.

**Comment by l29ah** [comment]
On Sat, Nov 04, 2017 at 02:28:52PM +0000, philip-bl wrote:
> Я сегодня залил немношк в быстроприготавливаемую овсянку, долил кипятка, и на вкус оно немношк охуело. Впрочем попробую еще залить после остывания и сравню на всяк. случай.

Поставь экспериментов с маслом vs маслом-с-кипятком лущ. По мне правда льняное масло искаропки яростно-мерзкое, и я не знаю как отличить зашкваренное. Судя по вкусу самостоятельно перемолотого льняного семени, это его нормальный вкус.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by l29ah** [comment]
https://en.wikipedia.org/wiki/Rancidification#Health_effects БЛЯ ХЗ)))

**Comment by l29ah** [comment]
10.1016/S0141-3910(99)00020-8 Fig. 2: it takes four hours at 80°C with forced air exchange for the flaxseed oil polymerization process to reach significant performance.
